'use client'

export default function Writing() {
    const articles = [
        {
            title: "Design of a Decision Support System Using the SAW Method to Determine the Best Teacher (Case Study: SDNLangenharjo 01)",
            abstract: "Education is an effective way to improve people's quality of life. The quality of education depends on the quality of the teachers who teach. Teachers have an important role in the growth and development of students at school. SDN Langenharjo 01 evaluates teacher performance in teaching students by selecting the best teachers as a form of appreciation for their performance and also as a form of teacher motivation to improve the quality of teaching students at school. The school still carries out manual calculation processes and does not yet use the system. The aim of this research is to develop a decision support system for determining the best teachers at SDN Langenharjo  01  using  the  web-based  Simple  Additive  Weighting  (SAW)  method.  This  research  uses  the  Agile System Development method, starting with initial planning, then continuing with the analysis and design stages, and ending with implementation and testing. The SAW method calculation shows that Raharja S.Pd is the best teacher with a preference value of 0.9913. Testing of system functionality shows that all functions in this decision support system work as expected",
            link: "https://journal.aptii.or.id/index.php/Modem/article/view/122/183",
            cover: "/writing/sampul1.png",
            journal: "Modem",
            year: "2024",
        },
        {
            title: "NLP Implementation For AI Generated Text Detection (ChatGPT) Using Naive Bayes Method",
            abstract: "The    rapid    advancement    of    artificial    intelligence    (AI), particularly  large  language  models  such  as  Chat-GPT,  has raised  concerns  regarding  the  authenticity  and  validity  of digital  content.  The  ability  of  AI  to  generate  human-like  text introduces    risks    of    misuse,    including    plagiarism    and information  manipulation.  This  study  aims  to  develop  an  AI-generated  text  detection  system  using  the  Multinomial  Naive Bayes  algorithm,  which  is  widely  used  for  text  classification due  to  its  simplicity  and  effectiveness.  TheHuman  Chat-GPT Comparison  Corpus  (H3C),  sourced  from  Reddit’s  r/ELI5 subreddit, was used as the dataset and contains 800 question-and-answer entries generated by both humans and AI. During the labeling process, responses were consolidated into a single column     and     assigned     labels     based     on     their     origin. Preprocessing    steps    included    case    folding,    digit    and punctuation    removal,    tokenization,    stop-word    removal, normalization,  and  finalization.  Text  features  were  extracted using the TF-IDF method, limited to thetop 1,000 features. The model  was  trained  on  80%  of  the  data  and  tested  on  the remaining  20%.  The  results  showed  an  accuracy  of  93%, indicating   that   the   Naive   Bayes   algorithm   is   effective   in distinguishing  AI-generated  from  human-generated  text  and holds promise as an automated tool for AI content detection",
            link: "https://jurnal.ubhinus.ac.id/index.php/J-INTECH/article/view/2026/1119",
            cover: "/writing/sampul2.webp",
            journal: "J-INTECH",
            year: "2025",
        }
    ]

    return (
        <section className="w-[90%] mx-auto mt-16 overflow-x-hidden">
            <div className='text-center mb-[30px]'>
                <h1 className='text-4xl font-bold mb-2'>Research & Journal Publications</h1>
                <p className='text-gray-600'>A collection of academic journals and research papers I have written, focusing on technology, data analysis, and real-world problem solving.</p>
            </div>

            <div className="flex flex-col gap-16">
                {articles.map((item, index) => (
                    <div
                        key={index}
                        className={`
                flex flex-col md:flex-row
                items-center
                gap-10
                ${index % 2 !== 0 ? 'md:flex-row-reverse' : ''}
            `}
                    >
                        {/* Cover Image */}
                        <div className="w-[400px] h-full flex justify-center md:w-1/2">
                            <img
                                src={item.cover}
                                alt={item.title}
                                className="
                        w-[400px]
                        h-full
                        object-cover
                        rounded-2xl
                        shadow-xl
                        hover:scale-[0.9]
                        transition-all duration-500
                        scale-[0.8]
                    "
                            />
                        </div>

                        {/* Content */}
                        <div className="w-full md:w-1/2">
                            <div className="flex items-center gap-4 mb-3">
                                <span className="px-3 py-1 text-sm rounded-full bg-gray-100 border">
                                    {item.journal}
                                </span>
                                <span className="text-sm text-gray-500">
                                    {item.year}
                                </span>
                            </div>

                            <h2 className="text-2xl font-bold text-gray-900 mb-3">
                                {item.title}
                            </h2>

                            <p className="text-gray-600 leading-relaxed text-justify">
                                {item.abstract}
                            </p>

                            <a
                                href={item.link}
                                target="_blank"
                                className="
                        inline-block
                        text-[20px]
                        border border-blue-500
                        px-5
                        py-2
                        rounded-[25px]
                        mt-5
                        text-blue-600
                        font-semibold
                        hover:scale-[1.2]
                        transition-all duration-500
                    "
                            >
                                Read Full Paper →
                            </a>
                        </div>
                    </div>
                ))}
            </div>
        </section>
    );
}